name: Build
on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.17
      - run: go mod tidy
      - run: go build ./...
